# Except for the output and filename, what is left out is read from the defaults.yml file.
# Information about the data file
FileName:       './data/obs-03-06-2018/PSR_B2021+51-13:15.fits'

# Folding parameters
Folding:
  nbins:          500           # Number of bins for folding 
  nbinsdedisp:    500           # Number of bins for dedispersed profile

# Output parameters
Output:
  OutputDir:      './output'    # Will overwrite any old files without warning.
  SavePlots:      true          # Saves all relevant plots in OutputDir
  
# If not wanted, you can just set ChiFit to false, and nothing will be done:
# ChiFit: false

# Chifit parameters
ChiFit:
   Ntries:       1000           # How many periods to calculate the average over
   nbins_time:   1000           # Amount of time bins to be used for calculating chisquared
   nbins_freq:   1000           # Amount of freq  bins to be used for calculating chisquared
   trywidth:     1e-3           # Time width of the period tries: (1-width)P_lit<P_try<(1+width)P_lit
   FitFunc:      'Lorentzian'   # Fit function to fit to the chisq as function of trial period. If left empty, will try all and prompt the user. 
 

# RFI removal scheme
GrasMaaier: {} # {} (empty dict) implies default params!
